# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jclockedio < Formula
  desc "This is a things for clocked in/out to Jobcan, then it results are send to Chatwork."
  homepage "https://github.com/masa0221/jclockedio"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/masa0221/jclockedio/releases/download/v0.2.4/jclockedio_darwin_arm64.zip"
      sha256 "0dc11be49a5251a7243091f1f6ce8ab40cca89d6ca97464272198389ca91a9f2"

      def install
        bin.install "jclockedio"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/masa0221/jclockedio/releases/download/v0.2.4/jclockedio_darwin_amd64.zip"
      sha256 "5db1fe8cca086e163cf159778743ec5951cef50bfbdc6ef4a77d50e276320739"

      def install
        bin.install "jclockedio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/masa0221/jclockedio/releases/download/v0.2.4/jclockedio_linux_amd64.zip"
      sha256 "cd13a7836e814797d83a6fa9d53ee1da61f3eef9ea12ed82409f62763561233c"

      def install
        bin.install "jclockedio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masa0221/jclockedio/releases/download/v0.2.4/jclockedio_linux_arm64.zip"
      sha256 "2b1fa2c79cf7479b172be1402d62d409543df9371bcfed4daf9195383a02888f"

      def install
        bin.install "jclockedio"
      end
    end
  end

  depends_on "chromedriver"
end
