# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jclockedio < Formula
  desc "This is a things for clocked in/out to Jobcan"
  homepage "https://github.com/masa0221/jclockedio"
  version "0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/masa0221/jclockedio/releases/download/v0.2.7/jclockedio_darwin_arm64.zip"
      sha256 "b94e21e773f5614fefba4ea950844587b16b8958c94eadeee4eef8ea9bc81175"

      def install
        bin.install "jclockedio"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/masa0221/jclockedio/releases/download/v0.2.7/jclockedio_darwin_amd64.zip"
      sha256 "d64c1ab59338c2e773055d24f8689503c809670d46f402a21876d5ded49f4fe5"

      def install
        bin.install "jclockedio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/masa0221/jclockedio/releases/download/v0.2.7/jclockedio_linux_amd64.zip"
      sha256 "b26190085c20cbb718843b2e90fdfa76c845276139d52ce255619fcf3d45b503"

      def install
        bin.install "jclockedio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masa0221/jclockedio/releases/download/v0.2.7/jclockedio_linux_arm64.zip"
      sha256 "ea59e2d51f85501088e6c3af86e43fc41aeb3d87659dc4595b38220b7bb7f2bf"

      def install
        bin.install "jclockedio"
      end
    end
  end
end
