# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jclockedio < Formula
  desc "This is a things for clocked in/out to Jobcan"
  homepage "https://github.com/masa0221/jclockedio"
  version "0.2.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/masa0221/jclockedio/releases/download/v0.2.10/jclockedio_darwin_arm64.zip"
      sha256 "0938ebcd340603e0e10533da4763a4695e82035954c0e1c86d9b1f2f3c0a2fb7"

      def install
        bin.install "jclockedio"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/masa0221/jclockedio/releases/download/v0.2.10/jclockedio_darwin_amd64.zip"
      sha256 "098d6106d55780b6f8e993ce301be8b461e1fbed02ccbcc4883aab8b6ef7750f"

      def install
        bin.install "jclockedio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/masa0221/jclockedio/releases/download/v0.2.10/jclockedio_linux_amd64.zip"
      sha256 "40b42a3844ee4d20aa00c6047bbd505ef8c3f13d30e0b24bfd35687fe2bb7210"

      def install
        bin.install "jclockedio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masa0221/jclockedio/releases/download/v0.2.10/jclockedio_linux_arm64.zip"
      sha256 "a51ce0f1339f796585293947902eb17b20aaaed76381c9e0700c6228e97df0d9"

      def install
        bin.install "jclockedio"
      end
    end
  end
end
